From ubuntu:16.04.3 LTS

MAINTAINER Deepthi

RUN apt-get update -y && apt-get install -y apache2 && apt-get clean && rm -rf /var/lib/apt/lists/*
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
COPY Demo/ /var/www/html
EXPOSE 80
